language: go

go:
  - 1.5
  - 1.6.2

install:
  - # WAV loading
  - go get github.com/youpy/go-riff
  - # Testing
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/mock
  - # Logging
  - go get github.com/Sirupsen/logrus

